/**********************************************************************
 *
 *    FILE:            TextureBuffer.cpp
 *
 *    DESCRIPTION:    Read/Write osg::TextureBuffer in binary format to disk.
 *
 *    CREATED BY:        Auto generated by iveGenerated
 *                    and later modified by Rune Schmidt Jensen.
 *
 *    HISTORY:        Created 20.3.2003
 *
 *    Copyright 2003 VR-C
 **********************************************************************/

#include "Exception.h"
#include "TextureBuffer.h"
#include "Texture.h"
#include "Image.h"

using namespace ive;

void TextureBuffer::write(DataOutputStream* out){
    // Write TextureBuffer's identification.
    out->writeInt(IVETEXTUREBUFFER);
    // If the osg class is inherited by any other class we should also write this to file.
    osg::Texture*  tex = dynamic_cast<osg::Texture*>(this);
    if(tex){
        ((ive::Texture*)(tex))->write(out);
    }
    else
        out_THROW_EXCEPTION("TextureBuffer::write(): Could not cast this osg::TextureBuffer to an osg::Texture.");
    // Write TextureBuffer's properties.
    // Write image.

    // Should we include images date in stream
    out->writeImage(getImage());
}

void TextureBuffer::read(DataInputStream* in){
    // Read TextureBuffer's identification.
    int id = in->peekInt();
    if(id == IVETEXTUREBUFFER){
        // Code to read TextureBuffer's properties.
        id = in->readInt();
        // If the osg class is inherited by any other class we should also read this from file.
        osg::Texture*  tex = dynamic_cast<osg::Texture*>(this);
        if(tex){
            ((ive::Texture*)(tex))->read(in);
        }
        else
            in_THROW_EXCEPTION("TextureBuffer::read(): Could not cast this osg::TextureBuffer to an osg::Texture.");
        // Read image.

        osg::Image *image = in->readImage();
        if(image) {
            setImage(image);
        }
    }
    else{
        in_THROW_EXCEPTION("TextureBuffer::read(): Expected TextureBuffer identification.");
    }
}
